// GET PROGRESS DATA
export const GET_DATA_PROGRESS_REQUEST = 'GET_DATA_PROGRESS_REQUEST';
export const GET_DATA_PROGRESS_SUCCESS = 'GET_DATA_PROGRESS_SUCCESS';
export const GET_DATA_PROGRESS_FAILED = 'GET_DATA_PROGRESS_FAILED';